const $ = selector => document.querySelector(selector);
const api = (path, options = {}) => { const isUpload = options.body instanceof FormData; return fetch(path, {headers: isUpload ? (options.headers || {}) : {"Content-Type": "application/json", ...(options.headers || {})}, ...options}).then(async response => { const body = await response.json().catch(() => ({})); if (!response.ok) throw Error(body.detail || "Something went wrong"); return body; }); };
let campaigns = [], calls = [], metrics = null, settings = {}, playbooks = [], audioAssets = [], activeReviewId = null, editingPlaybookId = null;
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const humanStatus = value => ({draft:"Ready to start",active:"Calls running",paused:"Paused",completed:"Completed"}[value] || value);
const humanCallStatus = value => ({queued:"Ready to call",calling:"Calling",ringing:"Ringing",answered:"Answered",completed:"Completed",failed:"Could not connect"}[value] || "Needs attention");
const humanOutcome = value => ({sale:"Sale",lead:"Lead",reject:"Not interested",wrong_number:"Wrong number"}[value] || "Needs review");
const formatDuration = seconds => seconds ? `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}` : '—';
const formatTime = value => value ? new Intl.DateTimeFormat(undefined, {month:'short', day:'numeric', hour:'numeric', minute:'2-digit'}).format(new Date(value)) : '—';

function setDate(){ $('#today-date').textContent = new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase(); }
function activeCampaign(){ return campaigns.find(c => c.status === 'active') || campaigns[0]; }
function pendingReviews(){ return calls.filter(call => call.status === 'completed' && !call.outcome); }
function initials(name){ return (name || 'Unknown').split(/\s+/).map(word => word[0]).join('').slice(0,2).toUpperCase(); }
function updateTop(){ const total = calls.length, complete = calls.filter(c => c.status === 'completed').length, review = pendingReviews().length, positive = (metrics.outcomes.sale || 0) + (metrics.outcomes.lead || 0); const percent = total ? Math.round(complete / total * 100) : 0;
  $('#calls').textContent = complete; $('#positive-outcomes').textContent = positive; $('#positive-detail').textContent = positive ? `${metrics.outcomes.sale || 0} sales · ${metrics.outcomes.lead || 0} leads` : 'waiting for outcomes'; $('#rate').textContent = `${metrics.conversion_rate || 0}%`; $('#rate-detail').textContent = metrics.outcomes.sale ? 'from labelled calls' : 'from your sales so far';
  $('#progress-number').textContent = complete; $('#progress-total').textContent = total; $('#progress-ring').style.background = `conic-gradient(#c2ecd9 ${percent * 3.6}deg,#ffffff28 0deg)`; $('#progress-label').textContent = total ? `${percent}% of today’s list complete` : 'Nothing scheduled yet';
  const campaign = activeCampaign(); const primary = $('#primary-action'), secondary = $('#secondary-action');
  if (!campaign) { $('#campaign-summary').textContent = 'Your calling day is ready when you are.'; $('#next-step-title').textContent = 'Set up your first calling day'; $('#next-step-detail').textContent = 'Create a campaign, add your prospect list, then let the system handle the calls.'; primary.textContent = 'Create a campaign  →'; primary.onclick = openDialog; secondary.hidden = true; }
  else if (review) { $('#campaign-summary').textContent = `${campaign.name} is ready for a quick review.`; $('#next-step-title').textContent = `${review} call${review === 1 ? '' : 's'} need your decision`; $('#next-step-detail').textContent = 'Choose what happened in each call. This is how the system learns what works.'; primary.textContent = 'Review calls  →'; primary.onclick = scrollToReviews; secondary.hidden = true; }
  else if (campaign.status === 'active') { $('#campaign-summary').textContent = `${campaign.name} is calling your prospects.`; $('#next-step-title').textContent = 'Your calls are under way'; $('#next-step-detail').textContent = total ? 'We will let you know as soon as calls are ready for your review.' : 'Add a prospect list before starting the first call batch.'; primary.textContent = 'Calls are running'; primary.onclick = () => {}; secondary.hidden = false; secondary.textContent = 'Pause calls'; secondary.onclick = () => campaignAction(campaign.id, 'pause'); }
  else { $('#campaign-summary').textContent = `${campaign.name} is ready to go.`; $('#next-step-title').textContent = 'Start your calling day'; $('#next-step-detail').textContent = total ? `Your list has ${total} prospect${total === 1 ? '' : 's'} ready for calls.` : 'Next, add your prospect list to begin.'; primary.textContent = 'Start calls  →'; primary.onclick = () => campaignAction(campaign.id, 'launch'); secondary.hidden = true; }
}
function renderReviews(){ const pending = pendingReviews(), root = $('#review-list'); if (activeReviewId && !pending.some(call => call.id === activeReviewId)) activeReviewId = null; $('#review-count').textContent = pending.length; $('#review-intro').textContent = pending.length ? 'Give each completed call a simple outcome. It takes less than a minute.' : 'When calls are finished, their outcomes will appear here for a quick review.'; root.innerHTML = pending.slice(0,3).map(call => { const open = call.id === activeReviewId; return `<div class="review-row ${open ? 'review-open' : ''}"><span class="avatar">${initials(call.prospect_name)}</span><div><strong>${escapeHtml(call.prospect_name || 'Unknown prospect')}</strong><small>${call.duration_seconds ? `${Math.floor(call.duration_seconds/60)}:${String(call.duration_seconds%60).padStart(2,'0')} call` : 'Call complete'} · Ready for review</small></div><button class="secondary-button small" data-review="${call.id}">${open ? 'Choose outcome' : 'Review'}</button>${open ? `<div class="outcome-picker"><p>What happened?</p><div><button data-outcome="sale" data-call="${call.id}">Sale</button><button data-outcome="lead" data-call="${call.id}">Lead</button><button data-outcome="reject" data-call="${call.id}">Not interested</button><button data-outcome="wrong_number" data-call="${call.id}">Wrong number</button></div></div>` : ''}</div>`; }).join(''); $('#review-now').hidden = !pending.length; root.querySelectorAll('[data-review]').forEach(button => button.onclick = () => { activeReviewId = Number(button.dataset.review); renderReviews(); }); root.querySelectorAll('[data-outcome]').forEach(button => button.onclick = () => labelCall(button.dataset.call, button.dataset.outcome)); $('#review-now').onclick = () => { activeReviewId = pending[0]?.id; renderReviews(); }; }
function renderLearning(){ const reviewed = calls.filter(c => c.outcome).length, score = metrics.scores.engagement; if (!reviewed) return; $('#learning-title').textContent = score ? `Conversations are ${score >= 7 ? 'engaging prospects' : 'ready for closer attention'}` : 'Your calls are starting to tell a story'; $('#learning-copy').textContent = score ? `The current engagement score is ${score}/10. Keep labelling calls so we can recommend one specific improvement for the next script.` : 'The more outcomes you confirm, the clearer tomorrow’s recommendation will be.'; $('#learning-status').textContent = `${reviewed} call${reviewed === 1 ? '' : 's'} labelled`; }
function renderCampaigns(){ const root = $('#campaigns'); if (!campaigns.length) { root.innerHTML = '<div class="empty-campaigns">No campaigns yet. Create one when you are ready to make your first calls.</div>'; return; } root.innerHTML = campaigns.map(campaign => `<article class="campaign-row"><span class="status-dot ${campaign.status === 'active' ? 'active' : ''}"></span><div><strong>${escapeHtml(campaign.name)}</strong><small>${humanStatus(campaign.status)}</small></div><div class="actions">${campaign.status === 'active' ? `<button class="secondary-button small" data-pause="${campaign.id}">Pause</button>` : `<button class="secondary-button small" data-launch="${campaign.id}">${campaign.status === 'draft' ? 'Start calls' : 'Resume calls'}</button>`}<button class="quiet-button" data-simulate="${campaign.id}">Run test batch</button></div></article>`).join(''); root.querySelectorAll('[data-launch]').forEach(b => b.onclick = () => campaignAction(b.dataset.launch,'launch')); root.querySelectorAll('[data-pause]').forEach(b => b.onclick = () => campaignAction(b.dataset.pause,'pause')); root.querySelectorAll('[data-simulate]').forEach(b => b.onclick = () => campaignAction(b.dataset.simulate,'run-simulation')); }
function renderCallLog(){ const root = $('#call-log-list'), labelled = calls.filter(call => call.outcome).length, completed = calls.filter(call => call.status === 'completed').length; $('#call-log-count').textContent = `${calls.length} call${calls.length === 1 ? '' : 's'}`; $('#log-summary').innerHTML = `<article><strong>${completed}</strong><span>completed</span></article><article><strong>${labelled}</strong><span>labelled</span></article><article><strong>${Math.max(completed - labelled, 0)}</strong><span>need review</span></article>`; if (!calls.length) { root.innerHTML = '<div class="empty-call-log"><span>☎</span><h2>Your call log is ready</h2><p>When calls begin, you will see each one here with a clear status and outcome.</p></div>'; return; } root.innerHTML = calls.map(call => { const campaign = campaigns.find(item => item.id === call.campaign_id), canLabel = call.status === 'completed' && !call.outcome, snapshot = call.configuration_snapshot_json || {}; const playbook = snapshot.playbook || {}, playbookName = playbook.name, version = playbook.version; const failure = call.failure_reason; return `<article class="call-row"><div class="call-time">${formatTime(call.created_at)}</div><div class="call-person"><span class="avatar">${initials(call.prospect_name)}</span><div><strong>${escapeHtml(call.prospect_name || 'Unknown contact')}</strong><small>${escapeHtml(call.phone)}</small></div></div><div class="call-campaign"><strong>${escapeHtml(campaign?.name || 'Campaign')}</strong><small>${playbookName ? `${escapeHtml(playbookName)}${version ? ` · v${version}` : ''}` : 'Campaign'}</small></div><div><span class="status-pill ${escapeHtml(call.status)}">${humanCallStatus(call.status)}</span>${failure ? `<small class="failure-note">${escapeHtml(failure)}</small>` : ''}</div><div class="call-duration"><strong>${formatDuration(call.duration_seconds)}</strong><small>duration</small></div><div class="recording-state"><span>${call.recording_available ? '◉' : '◌'}</span><small>${call.recording_available ? 'Recording available' : call.status === 'completed' ? 'No recording' : 'No recording yet'}</small></div><div class="call-outcome">${call.outcome ? `<span class="outcome-tag ${escapeHtml(call.outcome)}">${humanOutcome(call.outcome)}</span>` : canLabel ? `<button class="secondary-button small" data-log-review="${call.id}">Label outcome</button>` : '<small>—</small>'}</div></article>`; }).join(''); root.querySelectorAll('[data-log-review]').forEach(button => button.onclick = () => { activeReviewId = Number(button.dataset.logReview); showView('today'); setTimeout(scrollToReviews, 0); renderReviews(); }); }
function showView(name){ document.querySelectorAll('.app-view').forEach(view => view.classList.toggle('active-view', view.id === `${name}-view`)); document.querySelectorAll('.nav-link').forEach(link => link.classList.toggle('active', link.dataset.view === name)); if (name === 'call-log') renderCallLog(); window.scrollTo({top:0, behavior:'smooth'}); }
function settingValue(...keys){ return keys.map(key => settings[key]).find(value => value !== undefined && value !== null); }
function setFormValue(form, name, value){ if (value === undefined || value === null || !form[name]) return; if (form[name].type === 'checkbox') form[name].checked = Boolean(value); else form[name].value = String(value); }
function audioLabel(asset){ return asset.original_filename || asset.display_name || asset.name || `Audio ${asset.id}`; }
function playbookName(playbook){ return playbook.name || 'Untitled playbook'; }
function currentVersion(playbook){ return playbook.versions?.find(version => version.id === playbook.current_version_id) || playbook.versions?.[playbook.versions.length - 1]; }
function isApproved(playbook){ const version = currentVersion(playbook); return playbook.status === 'approved' && version?.status === 'approved'; }
function populateSelectors(){ const approved = playbooks.filter(isApproved); const campaignSelect = $('#campaign-playbook'), audioSelect = $('#playbook-audio'); campaignSelect.innerHTML = approved.length ? `<option value="">Choose an approved playbook</option>${approved.map(p => { const version = currentVersion(p); return `<option value="${version.id}">${escapeHtml(playbookName(p))} · v${version.version}</option>`; }).join('')}` : '<option value="">Create and approve a playbook first</option>'; campaignSelect.disabled = !approved.length; audioSelect.innerHTML = `<option value="">No prerecorded opening</option>${audioAssets.map(asset => `<option value="${asset.id}">${escapeHtml(audioLabel(asset))}</option>`).join('')}`; }
function renderPlaybooks(){ const root = $('#playbook-list'); if (!playbooks.length) { root.innerHTML = '<div class="empty-inline">Create one approved playbook before starting a campaign.</div>'; return; } root.innerHTML = playbooks.map(p => { const version = currentVersion(p), audio = audioAssets.find(asset => asset.id === version?.opening_audio_id); return `<div class="playbook-row"><div><strong>${escapeHtml(playbookName(p))}</strong><small>${isApproved(p) ? 'Approved for campaigns' : 'Draft — not available to campaigns'}${version ? ` · version ${version.version}` : ''}${audio ? ` · ${escapeHtml(audioLabel(audio))}` : ''}</small></div><div><span class="approval-tag ${isApproved(p) ? 'approved' : 'draft'}">${isApproved(p) ? 'Approved' : 'Draft'}</span><button class="quiet-button small" data-edit-playbook="${p.id}">New version</button></div></div>`; }).join(''); root.querySelectorAll('[data-edit-playbook]').forEach(button => button.onclick = () => openPlaybook(playbooks.find(p => String(p.id) === button.dataset.editPlaybook))); }
function renderAudioAssets(){ const root = $('#audio-list'); if (!audioAssets.length) { root.innerHTML = '<div class="empty-inline">No audio uploaded yet.</div>'; return; } root.innerHTML = audioAssets.map(asset => `<div class="audio-row"><div><strong>${escapeHtml(audioLabel(asset))}</strong><small>${escapeHtml(asset.content_type || asset.mime_type || 'Audio file')}${asset.size_bytes ? ` · ${Math.max(1, Math.round(asset.size_bytes / 1024))} KB` : ''}</small></div><button class="quiet-button small" data-delete-audio="${asset.id}">Remove</button></div>`).join(''); root.querySelectorAll('[data-delete-audio]').forEach(button => button.onclick = async () => { if (!confirm('Remove this audio file? Playbooks using it will need another opening message.')) return; try { await api(`/audio-assets/${button.dataset.deleteAudio}`, {method:'DELETE'}); await load(); } catch(error) { alert(error.message); } }); }
function openPlaybook(playbook = null){ editingPlaybookId = playbook?.id || null; const form = $('#playbook-form'), version = playbook ? currentVersion(playbook) : null; form.reset(); form.elements.id.value = editingPlaybookId || ''; $('#playbook-dialog-title').textContent = playbook ? `New version of ${playbookName(playbook)}` : 'Create a playbook'; setFormValue(form, 'name', playbook?.name); form.elements.name.disabled = Boolean(playbook); setFormValue(form, 'script', version?.script); setFormValue(form, 'audio_asset_id', version?.opening_audio_id); setFormValue(form, 'record_calls', version?.recording_enabled ?? true); setFormValue(form, 'approved', false); $('#playbook-dialog').showModal(); }
function setupSettings(){ const form = $('#settings-form'), window = settings.default_calling_window_json || {}; setFormValue(form, 'start-hour', window.start || '09:00'); setFormValue(form, 'end-hour', window.end || '17:00'); setFormValue(form, 'timezone', settings.default_timezone || 'Asia/Dubai'); setFormValue(form, 'concurrent', settings.max_concurrent_calls || metrics?.max_concurrent_calls || 1); setFormValue(form, 'retention', settings.recording_retention_days || 90); setFormValue(form, 'test-calling', settings.test_call_enabled ?? false); $('#connection-list').innerHTML = `<div><span class="connection-dot online"></span><strong>3CX calling</strong><small>${$('#health').textContent || 'Checking'}</small></div><div><span class="connection-dot online"></span><strong>Call log</strong><small>Saved privately on your server</small></div><div><span class="connection-dot online"></span><strong>Recordings</strong><small>Private storage is ready</small></div>`; form['test-calling'].onchange = event => { $('#test-call-note').textContent = event.target.checked ? 'Allowed — test calls still go only to your approved number.' : 'Locked — turn on only when you are ready to receive it.'; }; form.onsubmit = async event => { event.preventDefault(); const data = new FormData(form); const payload = {default_timezone:data.get('timezone'), default_calling_window_json:{start:data.get('start-hour'), end:data.get('end-hour')}, max_concurrent_calls:Number(data.get('concurrent')), recording_retention_days:Number(data.get('retention')), test_call_enabled:data.get('test-calling') === 'on'}; try { settings = await api('/settings', {method:'PUT', body:JSON.stringify(payload)}); $('#settings-saved').textContent = 'Settings saved.'; setTimeout(() => { $('#settings-saved').textContent = ''; }, 4000); } catch(error) { alert(error.message); } }; renderPlaybooks(); renderAudioAssets(); populateSelectors(); }
async function campaignAction(id, action){ try { await api(`/campaigns/${id}/${action}`, {method:'POST'}); await load(); } catch(error) { alert(error.message); } }
async function labelCall(id, outcome){ if (!id || !outcome) return; try { await api(`/calls/${id}/outcome`, {method:'POST',body:JSON.stringify({outcome})}); activeReviewId = null; await load(); } catch(error) { alert(error.message); } }
function scrollToReviews(){ $('.review-card').scrollIntoView({behavior:'smooth',block:'center'}); }
function openDialog(){ populateSelectors(); if (!playbooks.filter(isApproved).length) { showView('settings'); $('#settings-saved').textContent = 'Create and approve a playbook before creating a campaign.'; return; } $('#campaign-dialog').showModal(); }
async function load(){ const required = [api('/health'),api('/metrics/daily'),api('/campaigns'),api('/calls')]; const optional = [api('/settings').catch(() => ({})), api('/playbooks').catch(() => []), api('/audio-assets').catch(() => [])]; const [health, daily, campaignData, callData, settingData, playbookData, assetData] = await Promise.all([...required, ...optional]); campaigns = campaignData; calls = callData; settings = settingData || {}; playbooks = Array.isArray(playbookData) ? playbookData : (playbookData.items || []); audioAssets = Array.isArray(assetData) ? assetData : (assetData.items || []); metrics = {...daily, max_concurrent_calls: health.max_concurrent_calls}; $('#health').textContent = `${health.max_concurrent_calls} call lines ready`; $('#health').classList.add('online'); updateTop(); renderReviews(); renderLearning(); renderCampaigns(); renderCallLog(); setupSettings(); }
$('#new-campaign').onclick = openDialog; $('#campaign-add').onclick = openDialog; document.querySelectorAll('.cancel').forEach(button => button.onclick = () => $('#campaign-dialog').close()); document.querySelectorAll('.cancel-playbook').forEach(button => button.onclick = () => $('#playbook-dialog').close()); $('#new-playbook').onclick = () => openPlaybook(); $('#audio-upload').onchange = async event => { const file = event.target.files[0]; if (!file) return; if (!/\.(mp3|wav)$/i.test(file.name)) { alert('Please choose an MP3 or WAV file.'); event.target.value = ''; return; } const body = new FormData(); body.append('file', file); $('#audio-upload-note').textContent = `Uploading ${file.name}…`; try { await api('/audio-assets', {method:'POST', body}); $('#audio-upload-note').textContent = `${file.name} is ready to use.`; event.target.value = ''; await load(); } catch(error) { $('#audio-upload-note').textContent = 'Upload could not be completed.'; alert(error.message); } };
$('#playbook-form').onsubmit = async event => { event.preventDefault(); const data = new FormData(event.target); const payload = {script:data.get('script'), opening_audio_id:data.get('audio_asset_id') ? Number(data.get('audio_asset_id')) : null, recording_enabled:data.get('record_calls') === 'on', approve:data.get('approved') === 'on'}; try { if (editingPlaybookId) await api(`/playbooks/${editingPlaybookId}/versions`, {method:'POST',body:JSON.stringify(payload)}); else await api('/playbooks',{method:'POST',body:JSON.stringify({...payload, name:data.get('name')})}); $('#playbook-dialog').close(); await load(); } catch(error) { alert(error.message); } };
$('#campaign-form').onsubmit = async event => { event.preventDefault(); const data = new FormData(event.target); const max = data.get('max_concurrent_calls'); const payload = {name:data.get('name'), playbook_version_id:Number(data.get('playbook_id')), calling_window_json:{start:data.get('start_hour'), end:data.get('end_hour')}, timezone:data.get('timezone'), caller_id_override:data.get('caller_id') || null, max_concurrent_calls_override:max ? Number(max) : null}; try { await api('/campaigns',{method:'POST',body:JSON.stringify(payload)}); event.target.reset(); $('#campaign-dialog').close(); await load(); } catch(error) { alert(error.message); } };
document.querySelectorAll('.nav-link').forEach(link => link.onclick = () => showView(link.dataset.view));
$('#call-log-review').onclick = () => { showView('today'); setTimeout(scrollToReviews, 0); };
setDate(); load().catch(error => { $('#health').textContent = 'Dashboard is unavailable'; console.error(error); });
