const $ = selector => document.querySelector(selector);
const api = (path, options = {}) => fetch(path, {headers: {"Content-Type": "application/json", ...(options.headers || {})}, ...options}).then(async response => {if (!response.ok) throw Error((await response.json()).detail || "Something went wrong"); return response.json();});
let campaigns = [], calls = [], metrics = null, activeReviewId = null;
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const humanStatus = value => ({draft:"Ready to start",active:"Calls running",paused:"Paused",completed:"Completed"}[value] || value);

function setDate(){ $('#today-date').textContent = new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase(); }
function activeCampaign(){ return campaigns.find(c => c.status === 'active') || campaigns[0]; }
function pendingReviews(){ return calls.filter(call => call.status === 'completed' && !call.outcome); }
function initials(name){ return (name || 'Unknown').split(/\s+/).map(word => word[0]).join('').slice(0,2).toUpperCase(); }
function updateTop(){ const total = calls.length, complete = calls.filter(c => c.status === 'completed').length, review = pendingReviews().length, positive = (metrics.outcomes.sale || 0) + (metrics.outcomes.lead || 0); const percent = total ? Math.round(complete / total * 100) : 0;
  $('#calls').textContent = complete; $('#positive-outcomes').textContent = positive; $('#positive-detail').textContent = positive ? `${metrics.outcomes.sale || 0} sales · ${metrics.outcomes.lead || 0} leads` : 'waiting for outcomes'; $('#rate').textContent = `${metrics.conversion_rate || 0}%`; $('#rate-detail').textContent = metrics.outcomes.sale ? 'from labelled calls' : 'from your sales so far';
  $('#progress-number').textContent = complete; $('#progress-total').textContent = total; $('#progress-ring').style.background = `conic-gradient(#c2ecd9 ${percent * 3.6}deg,#ffffff28 0deg)`; $('#progress-label').textContent = total ? `${percent}% of today’s list complete` : 'Nothing scheduled yet';
  const campaign = activeCampaign(); const primary = $('#primary-action'), secondary = $('#secondary-action');
  if (!campaign) { $('#campaign-summary').textContent = 'Your calling day is ready when you are.'; $('#next-step-title').textContent = 'Set up your first calling day'; $('#next-step-detail').textContent = 'Create a campaign, add your prospect list, then let the system handle the calls.'; primary.textContent = 'Create a campaign  →'; primary.onclick = openDialog; secondary.hidden = true; }
  else if (review) { $('#campaign-summary').textContent = `${campaign.name} is ready for a quick review.`; $('#next-step-title').textContent = `${review} call${review === 1 ? '' : 's'} need your decision`; $('#next-step-detail').textContent = 'Choose what happened in each call. This is how the system learns what works.'; primary.textContent = 'Review calls  →'; primary.onclick = scrollToReviews; secondary.hidden = true; }
  else if (campaign.status === 'active') { $('#campaign-summary').textContent = `${campaign.name} is calling your prospects.`; $('#next-step-title').textContent = 'Your calls are under way'; $('#next-step-detail').textContent = total ? 'We will let you know as soon as calls are ready for your review.' : 'Add a prospect list before starting the first call batch.'; primary.textContent = 'Calls are running'; primary.onclick = () => {}; secondary.hidden = false; secondary.textContent = 'Pause calls'; secondary.onclick = () => campaignAction(campaign.id, 'pause'); }
  else { $('#campaign-summary').textContent = `${campaign.name} is ready to go.`; $('#next-step-title').textContent = 'Start your calling day'; $('#next-step-detail').textContent = total ? `Your list has ${total} prospect${total === 1 ? '' : 's'} ready for calls.` : 'Next, add your prospect list to begin.'; primary.textContent = 'Start calls  →'; primary.onclick = () => campaignAction(campaign.id, 'launch'); secondary.hidden = true; }
}
function renderReviews(){ const pending = pendingReviews(), root = $('#review-list'); if (activeReviewId && !pending.some(call => call.id === activeReviewId)) activeReviewId = null; $('#review-count').textContent = pending.length; $('#review-intro').textContent = pending.length ? 'Give each completed call a simple outcome. It takes less than a minute.' : 'When calls are finished, their outcomes will appear here for a quick review.'; root.innerHTML = pending.slice(0,3).map(call => { const open = call.id === activeReviewId; return `<div class="review-row ${open ? 'review-open' : ''}"><span class="avatar">${initials(call.prospect_name)}</span><div><strong>${escapeHtml(call.prospect_name || 'Unknown prospect')}</strong><small>${call.duration_seconds ? `${Math.floor(call.duration_seconds/60)}:${String(call.duration_seconds%60).padStart(2,'0')} call` : 'Call complete'} · Ready for review</small></div><button class="secondary-button small" data-review="${call.id}">${open ? 'Choose outcome' : 'Review'}</button>${open ? `<div class="outcome-picker"><p>What happened?</p><div><button data-outcome="sale" data-call="${call.id}">Sale</button><button data-outcome="lead" data-call="${call.id}">Lead</button><button data-outcome="reject" data-call="${call.id}">Not interested</button><button data-outcome="wrong_number" data-call="${call.id}">Wrong number</button></div></div>` : ''}</div>`; }).join(''); $('#review-now').hidden = !pending.length; root.querySelectorAll('[data-review]').forEach(button => button.onclick = () => { activeReviewId = Number(button.dataset.review); renderReviews(); }); root.querySelectorAll('[data-outcome]').forEach(button => button.onclick = () => labelCall(button.dataset.call, button.dataset.outcome)); $('#review-now').onclick = () => { activeReviewId = pending[0]?.id; renderReviews(); }; }
function renderLearning(){ const reviewed = calls.filter(c => c.outcome).length, score = metrics.scores.engagement; if (!reviewed) return; $('#learning-title').textContent = score ? `Conversations are ${score >= 7 ? 'engaging prospects' : 'ready for closer attention'}` : 'Your calls are starting to tell a story'; $('#learning-copy').textContent = score ? `The current engagement score is ${score}/10. Keep labelling calls so we can recommend one specific improvement for the next script.` : 'The more outcomes you confirm, the clearer tomorrow’s recommendation will be.'; $('#learning-status').textContent = `${reviewed} call${reviewed === 1 ? '' : 's'} labelled`; }
function renderCampaigns(){ const root = $('#campaigns'); if (!campaigns.length) { root.innerHTML = '<div class="empty-campaigns">No campaigns yet. Create one when you are ready to make your first calls.</div>'; return; } root.innerHTML = campaigns.map(campaign => `<article class="campaign-row"><span class="status-dot ${campaign.status === 'active' ? 'active' : ''}"></span><div><strong>${escapeHtml(campaign.name)}</strong><small>${humanStatus(campaign.status)}</small></div><div class="actions">${campaign.status === 'active' ? `<button class="secondary-button small" data-pause="${campaign.id}">Pause</button>` : `<button class="secondary-button small" data-launch="${campaign.id}">${campaign.status === 'draft' ? 'Start calls' : 'Resume calls'}</button>`}<button class="quiet-button" data-simulate="${campaign.id}">Run test batch</button></div></article>`).join(''); root.querySelectorAll('[data-launch]').forEach(b => b.onclick = () => campaignAction(b.dataset.launch,'launch')); root.querySelectorAll('[data-pause]').forEach(b => b.onclick = () => campaignAction(b.dataset.pause,'pause')); root.querySelectorAll('[data-simulate]').forEach(b => b.onclick = () => campaignAction(b.dataset.simulate,'run-simulation')); }
async function campaignAction(id, action){ try { await api(`/campaigns/${id}/${action}`, {method:'POST'}); await load(); } catch(error) { alert(error.message); } }
async function labelCall(id, outcome){ if (!id || !outcome) return; try { await api(`/calls/${id}/outcome`, {method:'POST',body:JSON.stringify({outcome})}); activeReviewId = null; await load(); } catch(error) { alert(error.message); } }
function scrollToReviews(){ $('.review-card').scrollIntoView({behavior:'smooth',block:'center'}); }
function openDialog(){ $('#campaign-dialog').showModal(); }
async function load(){ const [health, daily, campaignData, callData] = await Promise.all([api('/health'),api('/metrics/daily'),api('/campaigns'),api('/calls')]); campaigns = campaignData; calls = callData; metrics = daily; $('#health').textContent = `${health.max_concurrent_calls} call lines ready`; $('#health').classList.add('online'); updateTop(); renderReviews(); renderLearning(); renderCampaigns(); }
$('#new-campaign').onclick = openDialog; $('#campaign-add').onclick = openDialog; $('.cancel').onclick = () => $('#campaign-dialog').close(); $('#campaign-form').onsubmit = async event => { event.preventDefault(); const data = new FormData(event.target); try { await api('/campaigns',{method:'POST',body:JSON.stringify({name:data.get('name'),script:data.get('script')})}); event.target.reset(); $('#campaign-dialog').close(); await load(); } catch(error) { alert(error.message); } };
setDate(); load().catch(error => { $('#health').textContent = 'Dashboard is unavailable'; console.error(error); });
